apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.spring.profile }}
  SPRING_DATASOURCE_URL: {{ .Values.database.url }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers }}
