replicaCount: 2

image:
  tag: production

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

spring:
  profile: production

database:
  url: "jdbc:postgresql://postgres-production:5432/transferhub"

kafka:
  bootstrapServers: "kafka-production:9092"

hpa:
  minReplicas: 2
  maxReplicas: 8
  consumerLagThreshold: 500
