replicaCount: 2

image:
  tag: staging

resources:
  requests:
    memory: "384Mi"
    cpu: "200m"
  limits:
    memory: "768Mi"
    cpu: "750m"

spring:
  profile: staging

database:
  url: "jdbc:postgresql://postgres-staging:5432/transferhub"

kafka:
  bootstrapServers: "kafka-staging:9092"

hpa:
  minReplicas: 2
  maxReplicas: 5
  consumerLagThreshold: 500
