apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  GRPC_PORT: {{ .Values.grpc.port | quote }}
  HTTP_PORT: {{ .Values.http.port | quote }}
  REDIS_HOST: {{ .Values.redis.host }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
