apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  HTTP_PORT: {{ .Values.http.port | quote }}
  METRICS_PORT: {{ .Values.metrics.port | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers }}
