apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notification-gateway
spec:
  selector:
    app: notification-gateway
  ports:
    - name: http
      port: {{ .Values.http.port }}
      targetPort: {{ .Values.http.port }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
  type: ClusterIP
